services:
  postgres:
    image: postgres:16-alpine
    container_name: campusflow_db
    environment:
      POSTGRES_USER: campusflow
      POSTGRES_PASSWORD: campusflow_pass
      POSTGRES_DB: campusflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
